version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action*"
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
